# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sso
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Build
        run: go build -v ./cmd/sso

      - name: Build migrator
        run: go build -v ./cmd/migrator

      - name: Run migrator
        run: |
          ./migrator --db=postgres --migrations-path=./migrations/postgres/

      - name: Run
        run: |
          nohup ./sso --config=./config/local.yml &
          sleep 5 # wait for the server to start

      - name: Test
        run: go test -v ./tests/...
