# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Build
        run: go build -v ./cmd/sso

      - name: Build migrator
        run: go build -v ./cmd/migrator

      - name: Run migrator
        run: |
          ./migrator --storage-path=./storage/sso.db --migrations-path=./migrations/

      - name: Run
        run: |
          nohup ./sso --config=./config/local.yml &
          sleep 5 # wait for the server to start

      - name: Test
        run: go test -v ./tests/...
